# Generated by Django 5.0.4 on 2024-05-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_task_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='important',
            new_name='importante',
        ),
    ]
